name: "Build and Push Docker Image to ECR"
description: "Builds a Docker image and pushes it to Amazon ECR"
inputs:
  role-to-assume:
    description: "IAM role ARN to assume"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  ecr-repo:
    description: "ECR repository name"
    required: true
  image-name:
    description: "Name for the Docker image"
    required: true
  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: docker/Dockerfile
  context:
    description: "Docker build context"
    required: false
    default: ../

runs:
  using: "composite"
  steps:
    - name: Build Role Session Name
      shell: bash
      run: |
        REPO_NAME="${GITHUB_REPOSITORY##*/}"
        echo "SESSION_NAME=${REPO_NAME}-action-ecr" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ env.SESSION_NAME }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      shell: bash
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo }}:${{ inputs.image-name }}
        docker build -t $IMAGE_URI -f ${{ inputs.dockerfile }} ${{ inputs.context }}
        docker push $IMAGE_URI
